NaN === NaN;
Number.NaN === NaN;
isNaN(NaN);
isNaN(Number.NaN);
Number.isNaN(NaN);
console.log(NaN === NaN);
console.log(Number.NaN === NaN);
console.log(isNaN(NaN));    
console.log(isNaN(Number.NaN));
console.log(Number.isNaN(NaN));
